# Reproducible environment for RadixGraph experiments
FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /workspace

# ----------------------------
# System dependencies
# ----------------------------
RUN apt-get update && apt-get install -y \
    gcc-11 g++-11 \
    build-essential \
    cmake \
    git \
    libnuma-dev \
    libevent-dev \
    libboost-all-dev \
    zlib1g-dev \
    libsqlite3-dev \
    libpapi-dev \
    libjemalloc-dev \
    libtbb-dev \
    autoconf automake \
    python3 python3-pip python3-dev \
    wget curl ca-certificates

# Make gcc-11 / g++-11 default (matches notebook)
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100

# # Install TBB
# RUN wget https://github.com/uxlfoundation/oneTBB/archive/refs/tags/v2022.1.0.tar.gz && \
#   tar -xzf v2022.1.0.tar.gz && \
#   cd oneTBB-2022.1.0 && \
#   mkdir build && cd build && \
#   cmake .. -DCMAKE_BUILD_TYPE=Release && \
#   make -j$(nproc) && \
#   make install

# # Check whether TBB is installed correctly
# RUN nm /usr/lib/x86_64-linux-gnu/libtbb.so | grep -q "TBB_runtime_interface_version" || \
#     (echo "Error: TBB symbol TBB_runtime_interface_version not found!" >&2 && exit 1)

# ----------------------------
# Python dependencies
# ----------------------------
RUN apt-get install -y \
    python3-tqdm \
    python3-matplotlib \
    python3-numpy \
    python3-pandas

# ----------------------------
# Clone experiment repository
# ----------------------------
RUN git clone https://github.com/ForwardStar/gfe_driver.git

WORKDIR /workspace/gfe_driver

# ----------------------------
# Dataset preparation
# ----------------------------
# Download LiveJournal and dota-league
RUN python3 downloader.py --download-lj-only && \
  sed -i -E 's/[[:space:]]+/ /g' datasets/*.txt && \
  mv datasets/com-lj.ungraph.txt datasets/com-lj.ungraph.el
WORKDIR /workspace/gfe_driver/datasets
RUN wget https://datasets.ldbcouncil.org/graphalytics/dota-league.tar.zst && \
  tar -I zstd -xvf dota-league.tar.zst

# ----------------------------
# Configure GFE Driver
# ----------------------------
WORKDIR /workspace/gfe_driver
RUN git submodule update --init && \
    mkdir build && \
    cd build && \
    autoreconf -iv ..

# ----------------------------
# Generate vertex operations
# ----------------------------
WORKDIR /workspace/gfe_driver
RUN g++ scripts/create_vertex_ops.cpp -o create_vertex_ops -O3 && \
    ./create_vertex_ops

# ----------------------------
# Generate graphlog
# ----------------------------
WORKDIR /workspace/gfe_driver
RUN git clone https://github.com/MordorsElite/graphlog-base.git && \
    cd graphlog-base && \
    git submodule update --init && \
    mkdir build && \
    cd build && \
    cmake ../ -DCMAKE_BUILD_TYPE=Release && \
    make -j
WORKDIR /workspace/gfe_driver/graphlog-base/build
RUN ./graphlog -a 10 -e 1 -v 1 ../../datasets/dota-league.properties ../../dota-league.graphlog

# ----------------------------
# Generate property files
# ----------------------------
WORKDIR /workspace/gfe_driver
RUN g++ scripts/generate_property_files.cpp -o generate_property_files -O3 && \
    ./generate_property_files datasets/com-lj.ungraph.el && \
    ./generate_property_files datasets/dota-league.e

# ----------------------------
# Build RadixGraph
# ----------------------------
WORKDIR /workspace/gfe_driver/library/radixgraph/RadixGraph
RUN git submodule update --init --recursive && \
    cmake -S . -DCMAKE_BUILD_TYPE=Release && \
    make -j && \
    g++ optimizer.cpp -o optimizer -O3 && \
    mv optimizer ../../../ && \
    cd ../../../build && \
    ../configure --enable-optimize --disable-debug --enable-mem-analysis --with-radixgraph=../library/radixgraph/RadixGraph && \
    make clean && make -j

# ----------------------------
# Run RadixGraph experiments
# ----------------------------
# (1) Insertions, Deletions and Memory Consumptions
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_random.sh radixgraph 64
RUN sh scripts/run_vertex.sh radixgraph 64

# (2) Analytics
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_analytics.sh radixgraph 64

# (3) Concurrent reads and writes
WORKDIR /workspace/gfe_driver
RUN sed -i \
  -e 's/^#define[[:space:]]\+RUN_GET_NEIGHBORS[[:space:]]\+[01]/#define RUN_GET_NEIGHBORS 1/' \
  -e 's/^#define[[:space:]]\+RUN_TWO_HOP_NEIGHBORS[[:space:]]\+[01]/#define RUN_TWO_HOP_NEIGHBORS 0/' \
  configuration.hpp
WORKDIR /workspace/gfe_driver/build
RUN make -j
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_concurrent.sh radixgraph 64 && \
  mv results/radixgraph/concurrent results/radixgraph/concurrent-1-hop
RUN sed -i \
  -e 's/^#define[[:space:]]\+RUN_GET_NEIGHBORS[[:space:]]\+[01]/#define RUN_GET_NEIGHBORS 0/' \
  -e 's/^#define[[:space:]]\+RUN_TWO_HOP_NEIGHBORS[[:space:]]\+[01]/#define RUN_TWO_HOP_NEIGHBORS 1/' \
  configuration.hpp
WORKDIR /workspace/gfe_driver/build
RUN make -j
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_concurrent.sh radixgraph 64 && \
  mv results/radixgraph/concurrent results/radixgraph/concurrent-2-hop
RUN sed -i \
  -e 's/^#define[[:space:]]\+RUN_GET_NEIGHBORS[[:space:]]\+[01]/#define RUN_GET_NEIGHBORS 1/' \
  -e 's/^#define[[:space:]]\+RUN_TWO_HOP_NEIGHBORS[[:space:]]\+[01]/#define RUN_TWO_HOP_NEIGHBORS 1/' \
  configuration.hpp

# ----------------------------
# Build Spruce
# ----------------------------
# Firstly install junction
WORKDIR /workspace/gfe_driver
RUN git clone https://github.com/preshing/junction.git && \
    git clone https://github.com/preshing/turf.git && \
    cd junction && \
    mkdir build && \
    cd build && \
    cmake -DJUNCTION_WITH_SAMPLES=OFF .. && \
    make install
# Then build spruce
WORKDIR /workspace/gfe_driver
RUN wget -c https://github.com/Stardust-SJF/gfe_driver/releases/download/v2.0.0/libBVGT_stable.a && \
    mv libBVGT_stable.a libBVGT.a
RUN cd build && \
    ../configure --enable-optimize --enable-mem-analysis --disable-debug --with-bvgt=../ && \
    make clean && make -j

# ----------------------------
# Run Spruce experiments
# ----------------------------
# (1) Insertions, Deletions and Memory Consumptions
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_random.sh bvgt 64
RUN sh scripts/run_vertex.sh bvgt 64

# (2) Analytics
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_analytics.sh bvgt 64

# ----------------------------
# For the rest of experiments, disable twitter dataset
# ----------------------------
WORKDIR /workspace/gfe_driver
RUN sed -i '46s/^/# /' run_random.sh
RUN sed -i '46s/^/# /' run_vertex.sh
RUN sed -i '46s/^/# /' run_analytics.sh

# ----------------------------
# Build Teseo
# ----------------------------
WORKDIR /workspace/gfe_driver
RUN git clone https://github.com/cwida/teseo && \
    cd teseo && \
    autoreconf -iv && \
    mkdir build && \
    cd build && \
    ../configure --enable-optimize --disable-debug && \
    make -j && \
    cd ../../build && \
    ../configure --enable-optimize --disable-debug --enable-mem-analysis --with-teseo=../teseo/build && \
    make clean && make -j

# ----------------------------
# Run Teseo experiments
# ----------------------------
# (1) Insertions, Deletions and Memory Consumptions
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_random.sh teseo 64
RUN sh scripts/run_vertex.sh teseo 64

# (2) Analytics
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_analytics.sh teseo 64

# ----------------------------
# Build Sortledton
# ----------------------------
WORKDIR /workspace/gfe_driver
RUN git clone https://gitlab.db.in.tum.de/per.fuchs/sortledton && \
    cd sortledton && \
    git reset --hard && \
    sed -i '11d' CMakeLists.txt && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release .. && \
    make sortledton && \
    cd ../../build && \
    ../configure --enable-optimize --disable-debug --enable-mem-analysis --with-sortledton=../sortledton/build/ && \
    make clean && make -j

# ----------------------------
# Run Sortledton experiments
# ----------------------------
# (1) Insertions, Deletions and Memory Consumptions
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_random.sh sortledton 64
RUN sh scripts/run_vertex.sh sortledton 64

# (2) Analytics
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_analytics.sh sortledton 64

# ----------------------------
# Build GTX
# ----------------------------
WORKDIR /workspace/gfe_driver
RUN git clone https://github.com/Jiboxiake/GTX-SIGMOD2025 && \
  cd GTX-SIGMOD2025 && \
  git submodule update --init --recursive && \
  mkdir build && \
  cd build && \
  cmake -DCMAKE_BUILD_TYPE=Release .. && \
  make -j && \
  cd ../../build && \
  ../configure --enable-optimize --disable-debug --enable-mem-analysis --with-gtx=../GTX-SIGMOD2025/build && \
  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../GTX-SIGMOD2025/build && \
  make clean && make -j

# ----------------------------
# Run GTX experiments
# ----------------------------
# (1) Insertions, Deletions and Memory Consumptions
WORKDIR /workspace/gfe_driver
RUN export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./GTX-SIGMOD2025/build
RUN sh scripts/run_random.sh gtx 64
RUN sh scripts/run_vertex.sh gtx 64

# (2) Analytics
WORKDIR /workspace/gfe_driver
RUN export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./GTX-SIGMOD2025/build
RUN sh scripts/run_analytics.sh gtx 64

# (3) Concurrent reads and writes
WORKDIR /workspace/gfe_driver
RUN export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./GTX-SIGMOD2025/build
RUN sed -i \
  -e 's/^#define[[:space:]]\+RUN_GET_NEIGHBORS[[:space:]]\+[01]/#define RUN_GET_NEIGHBORS 1/' \
  -e 's/^#define[[:space:]]\+RUN_TWO_HOP_NEIGHBORS[[:space:]]\+[01]/#define RUN_TWO_HOP_NEIGHBORS 0/' \
  configuration.hpp
WORKDIR /workspace/gfe_driver/build
RUN make -j
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_concurrent.sh gtx 64 && \
  mv results/gtx/concurrent results/gtx/concurrent-1-hop
RUN sed -i \
  -e 's/^#define[[:space:]]\+RUN_GET_NEIGHBORS[[:space:]]\+[01]/#define RUN_GET_NEIGHBORS 0/' \
  -e 's/^#define[[:space:]]\+RUN_TWO_HOP_NEIGHBORS[[:space:]]\+[01]/#define RUN_TWO_HOP_NEIGHBORS 1/' \
  configuration.hpp
WORKDIR /workspace/gfe_driver/build
RUN make -j
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_concurrent.sh gtx 64 && \
  mv results/gtx/concurrent results/gtx/concurrent-2-hop
RUN sed -i \
  -e 's/^#define[[:space:]]\+RUN_GET_NEIGHBORS[[:space:]]\+[01]/#define RUN_GET_NEIGHBORS 1/' \
  -e 's/^#define[[:space:]]\+RUN_TWO_HOP_NEIGHBORS[[:space:]]\+[01]/#define RUN_TWO_HOP_NEIGHBORS 1/' \
  configuration.hpp

# ----------------------------
# Summarize data
# ----------------------------
WORKDIR /workspace/gfe_driver
RUN python3 scripts/data_to_csv.py

# ----------------------------
# Plot figures
# ----------------------------
WORKDIR /workspace/gfe_driver
RUN python3 scripts/plot_all_1.py
RUN python3 scripts/plot_all_2.py
RUN python3 scripts/plot_all_3.py
RUN printf "concurrent-1-hop\nconcurrent-2-hop\n" > concurrent_results.txt
RUN python3 scripts/plot_concurrent.py < ./concurrent_results.txt

# ----------------------------
# Default shell
# ----------------------------
WORKDIR /workspace/gfe_driver
CMD ["/bin/bash"]
