# Reproducible environment for RadixGraph experiments
FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /workspace

# ----------------------------
# System dependencies
# ----------------------------
RUN apt-get update && apt-get install -y \
    gcc-11 g++-11 \
    build-essential \
    cmake \
    git \
    libnuma-dev \
    libevent-dev \
    libboost-all-dev \
    zlib1g-dev \
    libsqlite3-dev \
    libpapi-dev \
    libjemalloc-dev \
    libtbb-dev \
    autoconf automake \
    python3 python3-pip python3-dev \
    wget curl ca-certificates

# Make gcc-11 / g++-11 default (matches notebook)
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100

# # Install TBB
# RUN wget https://github.com/uxlfoundation/oneTBB/archive/refs/tags/v2022.1.0.tar.gz && \
#   tar -xzf v2022.1.0.tar.gz && \
#   cd oneTBB-2022.1.0 && \
#   mkdir build && cd build && \
#   cmake .. -DCMAKE_BUILD_TYPE=Release && \
#   make -j$(nproc) && \
#   make install

# # Check whether TBB is installed correctly
# RUN nm /usr/lib/x86_64-linux-gnu/libtbb.so | grep -q "TBB_runtime_interface_version" || \
#     (echo "Error: TBB symbol TBB_runtime_interface_version not found!" >&2 && exit 1)

# ----------------------------
# Python dependencies
# ----------------------------
RUN pip3 install --no-cache-dir \
    tqdm \
    matplotlib \
    numpy \
    pandas

# ----------------------------
# Clone experiment repository
# ----------------------------
RUN git clone https://github.com/ForwardStar/gfe_driver.git

WORKDIR /workspace/gfe_driver

# ----------------------------
# Dataset preparation
# ----------------------------
# Full dataset pipeline (very slow).
# Comment this out if you want to prepare datasets manually at runtime.
RUN bash scripts/prepare_datasets.sh || true

# Remove duplicate edges (as in notebook)
RUN g++ scripts/remove_duplicate_edges.cpp -O3 -o remove_duplicate_edges || true && \
    ./remove_duplicate_edges ./datasets/twitter-2010.el || true

# ----------------------------
# Configure GFE Driver
# ----------------------------
RUN git submodule update --init && \
    mkdir build && \
    cd build && \
    autoreconf -iv ..

# ----------------------------
# Generate vertex operations
# ----------------------------
WORKDIR /workspace/gfe_driver
RUN g++ scripts/create_vertex_ops.cpp -o create_vertex_ops -O3 && \
    ./create_vertex_ops

# ----------------------------
# Generate graphlog
# ----------------------------
WORKDIR /workspace/gfe_driver
RUN git clone https://github.com/MordorsElite/graphlog-base.git && \
    cd graphlog-base && \
    git submodule update --init && \
    mkdir build && \
    cd build && \
    cmake ../ -DCMAKE_BUILD_TYPE=Release && \
    make -j
WORKDIR /workspace/gfe_driver/graphlog-base/build
RUN ./graphlog -a 1 -e 1 -v 1 ../../datasets/graph500-24.properties ../../graph500-24-delete.graphlog && \
    ./graphlog -a 1 -e 1 -v 1 ../../datasets/uniform-24.properties ../../uniform-24-delete.graphlog && \
    ./graphlog -a 10 -e 1 -v 1 ../../datasets/graph500-24.properties ../../graph500-24-1.0.graphlog && \
    ./graphlog -a 10 -e 1 -v 1 ../../datasets/uniform-24.properties ../../uniform-24-1.0.graphlog && \
    ./graphlog -a 10 -e 1 -v 1 ../../datasets/dota-league.properties ../../dota-league.graphlog

# ----------------------------
# Generate property files
# ----------------------------
WORKDIR /workspace/gfe_driver
RUN g++ scripts/generate_property_files.cpp -o generate_property_files -O3 && \
    ./generate_property_files datasets/twitter-2010.el && \
    ./generate_property_files datasets/com-lj.ungraph.el && \
    ./generate_property_files datasets/com-orkut.ungraph.el && \
    ./generate_property_files datasets/graph500-24.e && \
    ./generate_property_files datasets/uniform-24.e && \
    ./generate_property_files datasets/dota-league.e

# ----------------------------
# Build RadixGraph
# ----------------------------
WORKDIR /workspace/gfe_driver/library/radixgraph/RadixGraph
RUN git submodule update --init --recursive && \
    cmake -S . -DCMAKE_BUILD_TYPE=Release && \
    make -j && \
    g++ optimizer.cpp -o optimizer -O3 && \
    mv optimizer ../../../ && \
    cd ../../../build && \
    ../configure --enable-optimize --disable-debug --enable-mem-analysis --with-radixgraph=../library/radixgraph/RadixGraph && \
    make clean && make -j

# ----------------------------
# Run RadixGraph experiments
# ----------------------------
# (1) Insertions, Deletions and Memory Consumptions
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_random.sh radixgraph 64
RUN sh scripts/run_vertex.sh radixgraph 64

# (2) Mixed updates and delete-only
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_mixed.sh radixgraph 64
RUN sh scripts/run_delete_memfp.sh radixgraph 2

# (3) Analytics
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_analytics.sh radixgraph 64

# (4) Concurrent reads and writes
WORKDIR /workspace/gfe_driver
RUN sed -i \
  -e 's/^#define[[:space:]]\+RUN_GET_NEIGHBORS[[:space:]]\+[01]/#define RUN_GET_NEIGHBORS 1/' \
  -e 's/^#define[[:space:]]\+RUN_TWO_HOP_NEIGHBORS[[:space:]]\+[01]/#define RUN_TWO_HOP_NEIGHBORS 0/' \
  gfe_driver/configuration.hpp
WORKDIR /workspace/gfe_driver/build
RUN make -j
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_concurrent.sh radixgraph 64 && \
  mv results/radixgraph/concurrent results/radixgraph/concurrent-1-hop
RUN sed -i \
  -e 's/^#define[[:space:]]\+RUN_GET_NEIGHBORS[[:space:]]\+[01]/#define RUN_GET_NEIGHBORS 0/' \
  -e 's/^#define[[:space:]]\+RUN_TWO_HOP_NEIGHBORS[[:space:]]\+[01]/#define RUN_TWO_HOP_NEIGHBORS 1/' \
  gfe_driver/configuration.hpp
WORKDIR /workspace/gfe_driver/build
RUN make -j
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_concurrent.sh radixgraph 64 && \
  mv results/radixgraph/concurrent results/radixgraph/concurrent-2-hop
RUN sed -i \
  -e 's/^#define[[:space:]]\+RUN_GET_NEIGHBORS[[:space:]]\+[01]/#define RUN_GET_NEIGHBORS 1/' \
  -e 's/^#define[[:space:]]\+RUN_TWO_HOP_NEIGHBORS[[:space:]]\+[01]/#define RUN_TWO_HOP_NEIGHBORS 1/' \
  gfe_driver/configuration.hpp

# ----------------------------
# Build Spruce
# ----------------------------
# Firstly install junction
WORKDIR /workspace/gfe_driver
RUN git clone https://github.com/preshing/junction.git && \
    git clone https://github.com/preshing/turf.git && \
    cd junction && \
    mkdir build && \
    cd build && \
    cmake -DJUNCTION_WITH_SAMPLES=OFF .. && \
    make install
# Then build spruce
WORKDIR /workspace/gfe_driver
RUN wget -c https://github.com/Stardust-SJF/gfe_driver/releases/download/v2.0.0/libBVGT_stable.a && \
    mv libBVGT_stable.a libBVGT.a
RUN cd build && \
    ../configure --enable-optimize --enable-mem-analysis --disable-debug --with-bvgt=../
RUN make clean && make -j

# ----------------------------
# Run Spruce experiments
# ----------------------------
# (1) Insertions, Deletions and Memory Consumptions
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_random.sh bvgt 64
RUN sh scripts/run_vertex.sh bvgt 64

# (2) Mixed updates and delete-only
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_mixed.sh bvgt 64
RUN sh scripts/run_delete_memfp.sh bvgt 2

# (3) Analytics
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_analytics.sh bvgt 64

# (4) Concurrent reads and writes
WORKDIR /workspace/gfe_driver
RUN sed -i \
  -e 's/^#define[[:space:]]\+RUN_GET_NEIGHBORS[[:space:]]\+[01]/#define RUN_GET_NEIGHBORS 1/' \
  -e 's/^#define[[:space:]]\+RUN_TWO_HOP_NEIGHBORS[[:space:]]\+[01]/#define RUN_TWO_HOP_NEIGHBORS 0/' \
  gfe_driver/configuration.hpp
WORKDIR /workspace/gfe_driver/build
RUN make -j
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_concurrent.sh bvgt 64 && \
  mv results/bvgt/concurrent results/bvgt/concurrent-1-hop
RUN sed -i \
  -e 's/^#define[[:space:]]\+RUN_GET_NEIGHBORS[[:space:]]\+[01]/#define RUN_GET_NEIGHBORS 0/' \
  -e 's/^#define[[:space:]]\+RUN_TWO_HOP_NEIGHBORS[[:space:]]\+[01]/#define RUN_TWO_HOP_NEIGHBORS 1/' \
  gfe_driver/configuration.hpp
WORKDIR /workspace/gfe_driver/build
RUN make -j
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_concurrent.sh bvgt 64 && \
  mv results/bvgt/concurrent results/bvgt/concurrent-2-hop
RUN sed -i \
  -e 's/^#define[[:space:]]\+RUN_GET_NEIGHBORS[[:space:]]\+[01]/#define RUN_GET_NEIGHBORS 1/' \
  -e 's/^#define[[:space:]]\+RUN_TWO_HOP_NEIGHBORS[[:space:]]\+[01]/#define RUN_TWO_HOP_NEIGHBORS 1/' \
  gfe_driver/configuration.hpp
RUN sed -i \
  -e 's/^#define[[:space:]]\+RUN_GET_NEIGHBORS[[:space:]]\+[01]/#define RUN_GET_NEIGHBORS 1/' \
  -e 's/^#define[[:space:]]\+RUN_TWO_HOP_NEIGHBORS[[:space:]]\+[01]/#define RUN_TWO_HOP_NEIGHBORS 1/' \
  gfe_driver/configuration.hpp

# ----------------------------
# For the rest of experiments, disable twitter dataset
# ----------------------------
WORKDIR /workspace/gfe_driver
RUN sed -i '46s/^/# /' run_random.sh
RUN sed -i '46s/^/# /' run_vertex.sh
RUN sed -i '46s/^/# /' run_analytics.sh

# ----------------------------
# Build Teseo
# ----------------------------
WORKDIR /workspace/gfe_driver
RUN git clone https://github.com/cwida/teseo && \
    cd teseo && \
    autoreconf -iv && \
    mkdir build && \
    cd build && \
    ../configure --enable-optimize --disable-debug && \
    make -j && \
    cd ../../build && \
    ../configure --enable-optimize --disable-debug --enable-mem-analysis --with-teseo=../teseo/build && \
    make clean && make -j

# ----------------------------
# Run Teseo experiments
# ----------------------------
# (1) Insertions, Deletions and Memory Consumptions
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_random.sh teseo 64
RUN sh scripts/run_vertex.sh teseo 64

# (2) Mixed updates and delete-only
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_mixed.sh teseo 64
RUN sh scripts/run_delete_memfp.sh teseo 2

# (3) Analytics
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_analytics.sh teseo 64

# (4) Concurrent reads and writes
WORKDIR /workspace/gfe_driver
RUN sed -i \
  -e 's/^#define[[:space:]]\+RUN_GET_NEIGHBORS[[:space:]]\+[01]/#define RUN_GET_NEIGHBORS 1/' \
  -e 's/^#define[[:space:]]\+RUN_TWO_HOP_NEIGHBORS[[:space:]]\+[01]/#define RUN_TWO_HOP_NEIGHBORS 0/' \
  gfe_driver/configuration.hpp
WORKDIR /workspace/gfe_driver/build
RUN make -j
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_concurrent.sh teseo 64 && \
  mv results/teseo/concurrent results/teseo/concurrent-1-hop
RUN sed -i \
  -e 's/^#define[[:space:]]\+RUN_GET_NEIGHBORS[[:space:]]\+[01]/#define RUN_GET_NEIGHBORS 0/' \
  -e 's/^#define[[:space:]]\+RUN_TWO_HOP_NEIGHBORS[[:space:]]\+[01]/#define RUN_TWO_HOP_NEIGHBORS 1/' \
  gfe_driver/configuration.hpp
WORKDIR /workspace/gfe_driver/build
RUN make -j
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_concurrent.sh teseo 64 && \
  mv results/teseo/concurrent results/teseo/concurrent-2-hop
RUN sed -i \
  -e 's/^#define[[:space:]]\+RUN_GET_NEIGHBORS[[:space:]]\+[01]/#define RUN_GET_NEIGHBORS 1/' \
  -e 's/^#define[[:space:]]\+RUN_TWO_HOP_NEIGHBORS[[:space:]]\+[01]/#define RUN_TWO_HOP_NEIGHBORS 1/' \
  gfe_driver/configuration.hpp
RUN sed -i \
  -e 's/^#define[[:space:]]\+RUN_GET_NEIGHBORS[[:space:]]\+[01]/#define RUN_GET_NEIGHBORS 1/' \
  -e 's/^#define[[:space:]]\+RUN_TWO_HOP_NEIGHBORS[[:space:]]\+[01]/#define RUN_TWO_HOP_NEIGHBORS 1/' \
  gfe_driver/configuration.hpp

# ----------------------------
# Build Sortledton
# ----------------------------
WORKDIR /workspace/gfe_driver
RUN git clone https://gitlab.db.in.tum.de/per.fuchs/sortledton && \
    cd sortledton && \
    git reset --hard && \
    sed -i '11d' CMakeLists.txt && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release .. && \
    make sortledton && \
    cd ../../build && \
    ../configure --enable-optimize --disable-debug --enable-mem-analysis --with-sortledton=../sortledton/build/ && \
    make clean && make -j

# ----------------------------
# Run Sortledton experiments
# ----------------------------
# (1) Insertions, Deletions and Memory Consumptions
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_random.sh sortledton 64
RUN sh scripts/run_vertex.sh sortledton 64

# (2) Mixed updates and delete-only
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_mixed.sh sortledton 64
RUN sh scripts/run_delete_memfp.sh sortledton 2

# (3) Analytics
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_analytics.sh sortledton 64

# (4) Concurrent reads and writes
WORKDIR /workspace/gfe_driver
RUN sed -i \
    -e 's/^#define[[:space:]]\+RUN_GET_NEIGHBORS[[:space:]]\+[01]/#define RUN_GET_NEIGHBORS 1/' \
    -e 's/^#define[[:space:]]\+RUN_TWO_HOP_NEIGHBORS[[:space:]]\+[01]/#define RUN_TWO_HOP_NEIGHBORS 0/' \
    gfe_driver/configuration.hpp
WORKDIR /workspace/gfe_driver/build
RUN make -j
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_concurrent.sh sortledton 64 && \
    mv results/sortledton/concurrent results/sortledton/concurrent-1-hop
RUN sed -i \
    -e 's/^#define[[:space:]]\+RUN_GET_NEIGHBORS[[:space:]]\+[01]/#define RUN_GET_NEIGHBORS 0/' \
    -e 's/^#define[[:space:]]\+RUN_TWO_HOP_NEIGHBORS[[:space:]]\+[01]/#define RUN_TWO_HOP_NEIGHBORS 1/' \
    gfe_driver/configuration.hpp
WORKDIR /workspace/gfe_driver/build
RUN make -j
WORKDIR /workspace/gfe_driver
RUN sh scripts/run_concurrent.sh sortledton 64 && \
    mv results/sortledton/concurrent results/sortledton/concurrent-2-hop
RUN sed -i \
    -e 's/^#define[[:space:]]\+RUN_GET_NEIGHBORS[[:space:]]\+[01]/#define RUN_GET_NEIGHBORS 1/' \
    -e 's/^#define[[:space:]]\+RUN_TWO_HOP_NEIGHBORS[[:space:]]\+[01]/#define RUN_TWO_HOP_NEIGHBORS 1/' \
    gfe_driver/configuration.hpp
RUN sed -i \
    -e 's/^#define[[:space:]]\+RUN_GET_NEIGHBORS[[:space:]]\+[01]/#define RUN_GET_NEIGHBORS 1/' \
    -e 's/^#define[[:space:]]\+RUN_TWO_HOP_NEIGHBORS[[:space:]]\+[01]/#define RUN_TWO_HOP_NEIGHBORS 1/' \
    gfe_driver/configuration.hpp

# ----------------------------
# Default shell
# ----------------------------
WORKDIR /workspace/gfe_driver
CMD ["/bin/bash"]
